name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest  # Uses the latest Ubuntu runner

    steps:
      # ✅ Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Step 2: Login to GitHub Container Registry (GHCR) using Personal Access Token
      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      # ✅ Step 3: Build Docker image and tag for GHCR
      - name: Build Docker image
        run: |
          docker build . --file Dockerfile \
            --tag ghcr.io/zamibd/wiresocks:latest

      # ✅ Step 4: Push image to GitHub Container Registry (GHCR)
      - name: Push to GHCR
        run: docker push ghcr.io/zamibd/wiresocks:latest
